### ISSUE TITLE
very long filenames

### ISSUE THREAD

**Issue by ghost** [Lootyhoof/mozarchiver#1]
Not sure if bug or feature, but saving with very long filenames (i can confirm 643 chars long), give "unknown error". I've also made a terminal script to download and make maff, where the zip application cant handle very long file-name, dunno if its the same problem. (can be a problem since sometimes the default suggested name for the file is too long).

**Comment by Lootyhoof** [comment]
Could you give a website where this occurs? MozArchiver (and MAF) use the name provided to it by the browser generally, or retrieve it from the page title (depending on user preference).

**Comment by ghost** [comment]
try https://www.reddit.com/r/worldnews/comments/4d75i7/26_terabyte_leak_of_panamanian_shell_company_data/

**Comment by Lootyhoof** [comment]
Upon testing, it appears that Pale Moon cannot save pages such as this with the default name, even when simply saving as a standard HTML document.

This is a Pale Moon issue, and out of my control.
