### ISSUE TITLE
[EXPIRED] Incompatible with download extensions

### ISSUE THREAD

**Issue by sergeevabc** [Lootyhoof/mozarchiver#2]
Dear Ryan,
Could you be so kind to make MozArchiver compatible with download extensions such as [Automatic Save Folder][1] and [Download Sort][2]? They help us to sort files according to the specified rules. When one of them is present alongside Mozarchiver, neither “Save Page as”, nor “Save Page in Archive as” does not work.

[1]: http://asf.mangaheart.org/download.php?id=46&install=true
[2]: https://addons.mozilla.org/en-GB/firefox/addon/download-sort/

**Comment by Lootyhoof** [comment]
This requires edits on both ends (this extension and others), and is a known issue in the upstream extension also.

See [here](http://maf.mozdev.org/installation.html):

>The Download Sort extension has a known incompatibility with MAF. The conflict cannot be resolved without proper modifications to both extensions, and Download Sort is not actively maintained at this time.

**Comment by sergeevabc** [comment]
Let’s try to ping @cyan06, the author of [Automatic Save Folder][1] extension. We need this to be resolved as both tools make life more enjoyable, while currently user feels like a one-legged cripple dreaming of two.

[1]: https://github.com/cyan06/automatic-save-folder

**Comment by sergeevabc** [comment]
What changes do you expect or suggest, @Lootyhoof?

**Comment by Lootyhoof** [comment]
It will take time to study the code, as I'm not especially familiar with the code used for this feature. Please bear in mind that the previous statement came direct from upstream, so perhaps they could shed more light on the matter.
