### ISSUE TITLE
Can't save multiple tabs

### ISSUE THREAD

**Issue by geplus** [Lootyhoof/mozarchiver#4]
Hi,
when I try to save multiple tabs (more tabs at the same time separately or more tabs in a unique maff file), the operation fails.

**Comment by Lootyhoof** [comment]
Is there any output to the browser console (Ctrl+Shift+J)? What websites were you trying to archive?

I can't confirm this here, it works fine.

**Comment by geplus** [comment]
https://gist.github.com/geplus/a919d2bb60f831fadd11d191a45f8aed

site is www.complottisti.info

**Comment by Lootyhoof** [comment]
Nothing in that log seems to stand out (it's what's typical for a website).

What are the _exact_ steps you take to cause this issue?

You also mention one site specifically. Do you try to save several tabs from this one site?

**Comment by geplus** [comment]
I tried to save multiple pages from this website in one maff file

**Comment by Lootyhoof** [comment]
In what way did you try to do this, though? What commands did you perform and in what order? You also mentioned "more tabs at the same time separately" before. What did you do to do this?

**Comment by geplus** [comment]
It this exact moment I tried to save the pages disabling NoScript, uMatrix and Ublock, and they was saved succesfully.
The issue was probably caused by some blocked scripts.
Thank you for your attention!
