### ISSUE TITLE
Urlbar button does not work in PM 28

### ISSUE THREAD

**Issue by Ascrod** [Lootyhoof/mozarchiver#5]
After opening an archive file in Pale Moon 28.0.0b5, the button displayed in the URL bar does not function. On click, the following error is displayed in the console:
`TypeError: Ci.nsIPopupBoxObject is undefined`
The error occurs at [this line](https://github.com/Lootyhoof/mozarchiver/blob/66965c0a1c8d2991e069ce5b213dbe4ec09d73c2/src/chrome/content/integration/mafInterfaceOverlay.js#L102).

I suspect the root cause might be related to [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=979835). Replacing `Ci.nsIPopupBoxObject` with `PopupBoxObject` appears to fix the issue.

**Comment by Lootyhoof** [comment]
Looks like this does it. Thanks! Hadn't noticed this one when I got 2.0 out - I'll push a release soon enough with this fix included.
