### ISSUE TITLE
Feature request: Option to save original URL as comment at bottom of saved page.

### ISSUE THREAD

**Issue by stroobandt** [Lootyhoof/mozarchiver#7]
Coming from UnMHT, the only thing I miss is the option to save the original URL as comment at bottom of saved page.

![UnMHT URL comment option](https://i.imgur.com/9W0QSWa.png)

**Comment by Lootyhoof** [comment]
This information is already available in an infobar below the main browser UI. I see no reason for any other placement.

![Page URL](https://i.imgur.com/kA5Kx7W.png)

**Comment by stroobandt** [comment]
Sorry, my fault. Due to a remaining interaction with UnMHT, I was not seeing this.
